/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/email/mailboxes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List mailboxes
     * @description Returns every mailbox for the authenticated user, including folder counts.
     */
    get: operations['EmailController_getMailboxes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List emails
     * @description Paginated list of email summaries for a given mailbox. Defaults to the inbox.
     */
    get: operations['EmailController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/email/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get email by ID
     * @description Returns the full email including body content, headers, and metadata.
     */
    get: operations['EmailController_get'];
    put?: never;
    post?: never;
    /**
     * Delete an email
     * @description Permanently deletes an email by ID.
     */
    delete: operations['EmailController_delete'];
    options?: never;
    head?: never;
    /**
     * Update an email
     * @description Partially update an email: move it to another mailbox, mark as read/unread, or flag/unflag. Multiple operations can be combined in a single request.
     */
    patch: operations['EmailController_update'];
    trace?: never;
  };
  '/email/send': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Send an email
     * @description Composes and sends an email on behalf of the authenticated user. At least one recipient in `to` is required.
     */
    post: operations['EmailController_send'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/email/drafts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Save a draft
     * @description Creates a new draft email. All fields are optional so partial drafts can be saved.
     */
    post: operations['EmailController_saveDraft'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    MailboxResponseDto: {
      /** @example f3a1b2c4-… */
      id: string;
      /** @example Inbox */
      name: string;
      /**
       * @example inbox
       * @enum {string|null}
       */
      type: 'inbox' | 'drafts' | 'sent' | 'trash' | 'spam' | 'archive' | null;
      /** @example null */
      parentId: Record<string, never> | null;
      /** @example 142 */
      totalEmails: number;
      /** @example 3 */
      unreadEmails: number;
    };
    EmailAddressDto: {
      /** @example Alice Smith */
      name?: string;
      /** @example alice@internxt.me */
      email: string;
    };
    EmailSummaryResponseDto: {
      /** @example Ma1f09b… */
      id: string;
      /** @example T1a2b3c… */
      threadId: string;
      from: components['schemas']['EmailAddressDto'][];
      to: components['schemas']['EmailAddressDto'][];
      /** @example Weekly sync notes */
      subject: string;
      /** @example 2025-06-15T10:30:00Z */
      receivedAt: string;
      /** @example Hi team, here are the notes from… */
      preview: string;
      /** @example true */
      isRead: boolean;
      /** @example false */
      isFlagged: boolean;
      /** @example false */
      hasAttachment: boolean;
      /**
       * @description Size in bytes
       * @example 4096
       */
      size: number;
    };
    EmailListResponseDto: {
      emails: components['schemas']['EmailSummaryResponseDto'][];
      /**
       * @description Total emails in the mailbox
       * @example 142
       */
      total: number;
    };
    EmailResponseDto: {
      /** @example Ma1f09b… */
      id: string;
      /** @example T1a2b3c… */
      threadId: string;
      from: components['schemas']['EmailAddressDto'][];
      to: components['schemas']['EmailAddressDto'][];
      /** @example Weekly sync notes */
      subject: string;
      /** @example 2025-06-15T10:30:00Z */
      receivedAt: string;
      /** @example Hi team, here are the notes from… */
      preview: string;
      /** @example true */
      isRead: boolean;
      /** @example false */
      isFlagged: boolean;
      /** @example false */
      hasAttachment: boolean;
      /**
       * @description Size in bytes
       * @example 4096
       */
      size: number;
      cc: components['schemas']['EmailAddressDto'][];
      bcc: components['schemas']['EmailAddressDto'][];
      replyTo: components['schemas']['EmailAddressDto'][];
      /** @example 2025-06-15T10:29:55Z */
      sentAt: Record<string, never> | null;
      /** @example Hi team, here are the notes… */
      textBody: Record<string, never> | null;
      /** @example <p>Hi team, here are the notes…</p> */
      htmlBody: Record<string, never> | null;
    };
    SendEmailRequestDto: {
      /** @description Primary recipients (at least one required) */
      to: components['schemas']['EmailAddressDto'][];
      cc?: components['schemas']['EmailAddressDto'][];
      bcc?: components['schemas']['EmailAddressDto'][];
      /** @example Weekly sync notes */
      subject: string;
      /**
       * @description Plain-text version of the email body
       * @example Hi team, here are the notes from today…
       */
      textBody?: string;
      /**
       * @description HTML version of the email body
       * @example <p>Hi team, here are the notes from today…</p>
       */
      htmlBody?: string;
    };
    EmailCreatedResponseDto: {
      /**
       * @description ID of the created email
       * @example Ma1f09b…
       */
      id: string;
    };
    DraftEmailRequestDto: {
      to?: components['schemas']['EmailAddressDto'][];
      cc?: components['schemas']['EmailAddressDto'][];
      bcc?: components['schemas']['EmailAddressDto'][];
      /** @example Draft: project update */
      subject?: string;
      /** @example Still working on this… */
      textBody?: string;
      /** @example <p>Still working on this…</p> */
      htmlBody?: string;
    };
    UpdateEmailRequestDto: {
      /**
       * @description Move the email to this mailbox
       * @example trash
       * @enum {string}
       */
      mailbox?: 'inbox' | 'drafts' | 'sent' | 'trash' | 'spam' | 'archive';
      /**
       * @description Mark the email as read or unread
       * @example true
       */
      isRead?: boolean;
      /**
       * @description Flag or unflag the email
       * @example false
       */
      isFlagged?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EmailController_getMailboxes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MailboxResponseDto'][];
        };
      };
    };
  };
  EmailController_list: {
    parameters: {
      query?: {
        /** @description Mailbox to list. Defaults to `inbox`. */
        mailbox?: 'inbox' | 'drafts' | 'sent' | 'trash' | 'spam' | 'archive';
        /** @description Maximum number of emails to return. Defaults to `20`. */
        limit?: number;
        /** @description Zero-based offset for pagination. Defaults to `0`. */
        position?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EmailListResponseDto'];
        };
      };
    };
  };
  EmailController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EmailResponseDto'];
        };
      };
      /** @description Email not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EmailController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Email deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Email not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EmailController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateEmailRequestDto'];
      };
    };
    responses: {
      /** @description Email updated successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Email not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EmailController_send: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SendEmailRequestDto'];
      };
    };
    responses: {
      /** @description Email sent successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EmailCreatedResponseDto'];
        };
      };
    };
  };
  EmailController_saveDraft: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DraftEmailRequestDto'];
      };
    };
    responses: {
      /** @description Draft saved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EmailCreatedResponseDto'];
        };
      };
    };
  };
}
