name: Publish Package to npmjs
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Set the NPM registry with token
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Publish on NPM
        run: npm publish --scope=@internxt --access public
